### PR TITLE
Rename workflows

### PR DESCRIPTION
**Pull request by lmilbaum**

### CODE REVIEW

**Comment by lmilbaum** [comment]
@viceice Please review

**Review by viceice — COMMENTED** [review]
🤔I don't like `post-merge`

**Comment by viceice** [comment]
we need to change the license to agpl, like main renovate repo

**Comment by lmilbaum** [comment]
> 🤔I don't like `post-merge`

Don't like? 😎

**Comment by lmilbaum** [comment]
> we need to change the license to agpl, like main renovate repo

Will submit a separate PR

**Comment by lmilbaum** [comment]
> > 🤔I don't like `post-merge`
> 
> Don't like? 😎

With the hope that this name is likable :-)

**Review by viceice — APPROVED** [review]

**Pull request merged**
