### PR TITLE
Apply tags generated by docker/metadata-action

### PR DESCRIPTION
**Pull request by lmilbaum**

### CODE REVIEW

**Comment by lmilbaum** [comment]
@viceice Please review

**Review by viceice — APPROVED** [review]

**Comment by viceice** [comment]
please don't concentrate on these actions, well use semantic release and manual buildx calls to publish the images

**Comment by lmilbaum** [comment]
> please don't concentrate on these actions, well use semantic release and manual buildx calls to publish the images

I've tried to get familiar with how the semantic release code with no avail. It is not in my nature to blindly copy paste code.  Hence, I invest my cycles on solutions which might be easier to maintain.

**Comment by viceice** [comment]
> > please don't concentrate on these actions, well use semantic release and manual buildx calls to publish the images
> 
> I've tried to get familiar with how the semantic release code with no avail. It is not in my nature to blindly copy paste code.  Hence, I invest my cycles on solutions which might be easier to maintain.

the current solution wouldn't work in an good automated way, we would need a pat to push the git tag from main workflow to trigger the release workflow on git tag. we strongly want to avoid this on all circumstances.

that's why I said to use semantic release, which will allow us to push the tag, create the GitHub release and build / publish the docker tags.
I'll push the required stuff the next days.

**btw**: please use semantic commit titles for the PR's, so they are properly added to the changelog when we automate it.

**Comment by lmilbaum** [comment]
> > > please don't concentrate on these actions, well use semantic release and manual buildx calls to publish the images
> > 
> > 
> > I've tried to get familiar with how the semantic release code with no avail. It is not in my nature to blindly copy paste code.  Hence, I invest my cycles on solutions which might be easier to maintain.
> 
> the current solution wouldn't work in an good automated way, we would need a pat to push the git tag from main workflow to trigger the release workflow on git tag. we strongly want to avoid this on all circumstances.
> 
> that's why I said to use semantic release, which will allow us to push the tag, create the GitHub release and build / publish the docker tags. I'll push the required stuff the next days.
> 
> **btw**: please use semantic commit titles for the PR's, so they are properly added to the changelog when we automate it.

Thanks for the clarification. This is a valid argument. I'd suggest to improve the documentation.
BTW, how does the semantic release works on the following repo - renovatebot/docker-renovate ?

**Comment by viceice** [comment]
that repo currently doesn't use semantic release, it just follows renovate versions.

**Pull request merged**
